# Generated by Django 5.2.8 on 2025-12-11 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_quizattempt_fullscreen_exit_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('topic', models.CharField(max_length=100)),
                ('constraints', models.TextField(blank=True)),
                ('sample_input', models.TextField(blank=True)),
                ('sample_output', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('starter_code_python', models.TextField(blank=True)),
                ('starter_code_java', models.TextField(blank=True)),
                ('starter_code_cpp', models.TextField(blank=True)),
                ('starter_code_javascript', models.TextField(blank=True)),
                ('starter_code_c', models.TextField(blank=True)),
                ('time_limit', models.IntegerField(default=2)),
                ('memory_limit', models.IntegerField(default=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to='teachers.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('source_code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('runtime_error', 'Runtime Error'), ('time_limit', 'Time Limit Exceeded'), ('compilation_error', 'Compilation Error')], default='pending', max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('memory_used', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('friendly_hint', models.TextField(blank=True)),
                ('test_cases_passed', models.IntegerField(default=0)),
                ('test_cases_total', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teachers.codingproblem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=10)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='teachers.codingproblem')),
            ],
        ),
    ]
