# Generated by Django 5.2.8 on 2025-12-11 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_codingassignment_codingsubmission_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingassignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_assignments', to='teachers.subject'),
        ),
        migrations.AlterField(
            model_name='codingproblem',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to='teachers.subject'),
        ),
    ]
